CREATE TABLE IF NOT EXISTS Users(id INTEGER PRIMARY KEY AUTOINCREMENT, name  TEXT, age NUMBER);
INSERT or IGNORE INTO Users VALUES (1, 'Mimi', 21);
INSERT or IGNORE INTO Users VALUES (2, 'Miko', 21);
INSERT or IGNORE INTO Users VALUES (3, 'Kittina', 11);
